name: Deploy Flask App to Local Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies for linting and testing
      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install flake8 pytest

      # Step 3: Lint the code
      #- name: Lint Python code
      #  run: |
      #    source venv/bin/activate
      #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 4: Run tests
      #- name: Run Python tests
      #  run: |
      #    source venv/bin/activate
      #    pytest tests/

      # Step 5: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 6: Verify Docker setup
      - name: Set up Docker
        run: |
          docker version
          docker-compose version

      # Step 7: Remove existing Docker container (if it exists)
      - name: Remove existing Docker container
        run: |
          docker stop flask-app || true
          docker rm flask-app || true

      # Step 8: Build and deploy the container using docker-compose
      - name: Build and deploy Flask app
        run: |
          docker-compose up -d --build
